version: '3.8'

services:
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PEPPER=${PEPPER}
    volumes:
      - ./:/app

volumes:
  redis_data: