services:
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"

  web:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379